wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.18
    cli_version: 0.16.1
    framework: huggingface
    huggingface_version: 4.36.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1752244793.235933
    t:
      1:
      - 1
      - 9
      - 11
      - 49
      - 55
      - 103
      - 105
      2:
      - 1
      - 9
      - 11
      - 49
      - 55
      - 103
      - 105
      3:
      - 7
      - 13
      - 23
      4: 3.10.18
      5: 0.16.1
      6: 4.36.1
      8:
      - 5
      13: linux-x86_64
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: val_loss
      5: 1
      6:
      - 1
    - 1: val_pred_error
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: train_loss
      5: 1
      6:
      - 1
lat_size:
  desc: null
  value: 250
lon_size:
  desc: null
  value: 270
sog_size:
  desc: null
  value: 30
cog_size:
  desc: null
  value: 72
n_lat_embd:
  desc: null
  value: 256
n_lon_embd:
  desc: null
  value: 256
n_sog_embd:
  desc: null
  value: 128
n_cog_embd:
  desc: null
  value: 128
d_model:
  desc: null
  value: 768
n_head:
  desc: null
  value: 8
num_layers_enc:
  desc: null
  value: 3
num_layers_fus:
  desc: null
  value: 3
num_layers_dec:
  desc: null
  value: 3
dim_feedforward:
  desc: null
  value: 512
dropout:
  desc: null
  value: 0.1
max_len:
  desc: null
  value: 120
lr:
  desc: null
  value: 0.0001
