wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.18
    cli_version: 0.16.1
    framework: huggingface
    huggingface_version: 4.36.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1752241835.613184
    t:
      1:
      - 1
      - 9
      - 11
      - 49
      - 55
      - 103
      - 105
      2:
      - 1
      - 9
      - 11
      - 49
      - 55
      - 103
      - 105
      3:
      - 7
      - 13
      - 23
      4: 3.10.18
      5: 0.16.1
      6: 4.36.1
      8:
      - 5
      13: linux-x86_64
    m:
    - 1: trainer/global_step
      6:
      - 3
